### PR TITLE
soc_vwid: catch and handle permission error on open of reply file

### PR DESCRIPTION
**Pull request by rleidner**
Problem was reported a few times now - should be improved.
When open of reply file fails, "sudo rm reply file" and open it once more

### CODE REVIEW

**Comment by LKuemmel** [comment]
What is the reply file used for?
I couldn't find any piece of code that reads the reply file.

**Comment by rleidner** [comment]
The reply file is written to be used for diagnostics in support situations. 
If users report problems not getting the SOC we can ask to view at the reply file for details.

**Comment by LKuemmel** [comment]
Wouldn't it be a better solution to also include the status data in the main log at level 2, as all other modules do?

**Comment by rleidner** [comment]
"Wouldn't it be a better solution to also include the status data in the main log at level 2, as all other modules do?"

The content of the reply file is approx 320 lines json structure... not sure if that makes sense in the main log.

wrt. to status data in main log: can you please refer me to a EV SOC module which does logging in the expected way.
Please notice that only main.sh and soc_vwid.py can be modified. 
The core code (https://github.com/skagmo/ha_vwid/blob/main/custom_components/vwid/libvwid.py) is from another project and I currently do not plan to modify that without need.

Apart from that: All I wanted to do in this PR is to fix the issue where the reply file seems to be written under sudo during update and later user pi gets a permission error when overwriting that file.
I did not expect to have to discuss existing functionality ...

**Pull request merged**
