### PR TITLE
create python library with logger and config

### PR DESCRIPTION
**Pull request by yankee42**
There are a few things that are shared across a big number of scripts. I propose to create a shared library in order to de-duplicate code and encourage common patterns (e.g. for log outputs a common date/time format). (Similar to the `helperFunctions.sh`, but for python and not for bash).

One such thing shared across a lot of code is logging. Thus I started by creating a `Logger` that could be used application wide in all scripts. For starters I am using the library in the EVNotify SoC-Module.

### CODE REVIEW

**Comment by DetMoerk** [comment]
Have a Look at #1592 first, openWB is working on that.

**Comment by DetMoerk** [comment]
> Have a Look at #1592 first, openWB is working on that.

But I like your Logger implementation

**Comment by DetMoerk** [comment]
> > But I like your Logger implementation and also the config implementation.
> 
> Well, maybe it can then still serve a purpose.
> 
> I had a quick look at #1592, but that PR is HUGE... That will be tough to manage...

I agree. Release early and often would be better.

**Comment by DetMoerk** [comment]
I think yo can close that PR, as it is outdated

**Comment by benderl** [comment]
Ich denke auch, dass der PR nicht mehr benötigt wird. Falls doch, bitte melden.

**Pull request closed without merging**
