### PR TITLE
fix Fenecon storage energy values

### PR DESCRIPTION
**Pull request by sthhs**
Fix Fems datapoints. Tested with Fenecon Home system.

### CODE REVIEW

**Comment by dj3mu** [comment]
For me the difference in the values is ~0.007%. But there is a difference. However, I couldn't tell which of the values is the "more correct one".

Not that I don't trust the request. But I'd like to learn what's the difference between the two values. And unfortunately I cannot find documentation for it.

@sthhs Could you explain or point me to some kind of documentation? I'd really like to understand ...

**Comment by sthhs** [comment]
Unfortunately, there is no real documentation, but only the implementation page:
https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.ess.api/src/io/openems/edge/ess/api/HybridEss.java#L44-L67

But I can show the differences with some pictures.
This is the current state: 
before
Charge and discharge energy seem to be added.
This is the page of my Fems at the same moment:
fems
After changing the datapoints this is the resulting page:
after

There ist an answer from the responsible Fenecon developer: https://openwb.de/forum/viewtopic.php?p=73713#p73713
But the mentioned datapoints are only for the sum of all storage systems. My change considers that there are multiple storages possible.

**Comment by dj3mu** [comment]
Thanks for response and explanation. It seems I'm not the only one suffering from the "minimal documentation" provided with openEMS / FEMS.

My FEMS is stil version 2021.21.5. Inverter is 3-phase GoodWE attached to a BYD battery (hence an AC-coupled system).
As already said: Here the values are almost identical

But maybe the datapoints have changed in newer FEMS and Active*Energy did change meaning or have been corrected or discontinued.

Anyway: I'm looking forward to get this merged !

**Comment by sthhs** [comment]
OK, then this issue may only be valid for DC-coupled systems like mine with the GoodWe inverter, the CATL battery from 2022 and Fems Version 2022.10.x.

**Comment by benderl** [comment]
Is this PR ready for review and merge?
Do the provided changes apply to all models?

**Comment by sthhs** [comment]
> Is this PR ready for review and merge?
Yes
> Do the provided changes apply to all models?
Yes, I think so.

**Review by LKuemmel — APPROVED** [review]

**Pull request merged**
