### PR TITLE
python modules for counters

### PR DESCRIPTION
**Pull request by LKuemmel**

### CODE REVIEW

**Review by DetMoerk — COMMENTED** [review]
das bei read_json.py funktioniert so nicht. In den entsprechenden Variablen sind JQ Filter. 
Zum einen könnten diese, da sie Leerzeichen enthalten können, in einzelne Parameter zerlegt werden, zum Anderen muss dann innerhalb vom Python Teil mit jq gearbeitet werden.

Und wenn man die Module schon angreift, wäre ein Logging auch sinnvoll.



main.sh:
#!/bin/bash
OPENWBBASEDIR=$(cd `dirname $0`/../../ && pwd)
RAMDISKDIR="$OPENWBBASEDIR/ramdisk"
MODULEDIR=$(cd `dirname $0` && pwd)
#DMOD="EVU"
DMOD="MAIN"
Debug=$debug
MYLOGFILE="$RAMDISKDIR/evu_json.log"

python3 /var/www/html/openWB/modules/bezug_json/read_json.py "${bezugjsonurl}" "${bezugjsonwatt}" "${bezugjsonkwh}" "${einspeisungjsonkwh}" >>$MYLOGFILE 2>&1

#For development only
#Debug=1

openwbDebugLog ${DMOD} 2 "${bezugjsonwatt}"
openwbDebugLog ${DMOD} 2 "${bezugjsonkwh}"
openwbDebugLog ${DMOD} 2 "${einspeisungjsonkwh}"

#answer=$(curl --connect-timeout 5 -s $bezugjsonurl)
#evuwatt=$(echo $answer | jq -r "$bezugjsonwatt" | sed 's/\..*$//')
evuwatt=$(</var/www/html/openWB/ramdisk/wattbezug)
echo ${evuwatt}
openwbDebugLog  ${DMOD} 1 "Watt: ${evuwatt}"
#echo $evuwatt > /var/www/html/openWB/ramdisk/wattbezug
#
#if [ ! -z "${bezugjsonkwh}" ]; then
        #evuikwh=$(echo $answer | jq -r "$bezugjsonkwh")
#else
        #evuikwh=0
#fi
evuikwh=$(</var/www/html/openWB/ramdisk/bezugkwh)
openwbDebugLog ${DMOD} 1 "BezugkWh: ${evuikwh}"
#echo $evuikwh > /var/www/html/openWB/ramdisk/bezugkwh
#
#if [ ! -z "${einspeisungjsonkwh}" ]; then
        #evuekwh=$(echo $answer | jq -r "$einspeisungjsonkwh")
#else
        #evuekwh=0
#fi
evuekwh=$(</var/www/html/openWB/ramdisk/einspeisungkwh)
openwbDebugLog ${DMOD} 1 "EinspeiskWh: ${evuekwh}"
#echo $evuekwh > /var/www/html/openWB/ramdisk/einspeisungkwh

read_json.sh
#!/usr/bin/env python3

import requests
import sys
import traceback
import jq
from datetime import datetime, timezone


def DebugLog(message):
        local_time = datetime.now(timezone.utc).astimezone()
        print(local_time.strftime(format = "%Y-%m-%d %H:%M:%S") +": " + message)


bezugjsonurl = str(sys.argv[1])
bezugjsonwatt = str(sys.argv[2])
bezugjsonkwh = str(sys.argv[3])
einspeisungjsonkwh = str(sys.argv[4])

DebugLog('Watt: ' + bezugjsonwatt)
DebugLog('Bezug: ' + bezugjsonkwh)
DebugLog('Einsp: ' + einspeisungjsonkwh)


answer = requests.get(bezugjsonurl, timeout=5).json()
try:
        evuwatt = jq.compile(bezugjsonwatt).input(answer).first()
        #evuwatt = int(answer[bezugjsonwatt])
        with open("/var/www/html/openWB/ramdisk/wattbezug", "w") as f:
                f.write(str(evuwatt))
except:
        traceback.print_exc()

try:
        if bezugjsonkwh != "":
                evuikwh = jq.compile(bezugjsonkwh).input(answer).first()
                #evuikwh = answer[bezugjsonkwh]
        else:
                evuikwh = 0
        with open("/var/www/html/openWB/ramdisk/bezugkwh", "w") as f:
                f.write(str(evuikwh))
except:
        traceback.print_exc()

try:
        if einspeisungjsonkwh != "":
                evuekwh = jq.compile(einspeisungjsonkwh).input(answer).first()
                #evuekwh = answer[einspeisungjsonkwh]
        else:
                evuekwh = 0
        with open("/var/www/html/openWB/ramdisk/einspeisungkwh", "w") as f:
                f.write(str(evuekwh))
except:
        traceback.print_exc()

**Comment by DetMoerk** [comment]
Überarbeitete Versionen bezug_json:

main.sh:
`#!/bin/bash
OPENWBBASEDIR=$(cd `dirname $0`/../../ && pwd)
RAMDISKDIR="$OPENWBBASEDIR/ramdisk"
MODULEDIR=$(cd `dirname $0` && pwd)
#DMOD="EVU"
DMOD="MAIN"
Debug=$debug

#For development only
#Debug=1

if [ $DMOD == "MAIN" ]; then
        MYLOGFILE="$RAMDISKDIR/openWB.log"
else
        MYLOGFILE="$RAMDISKDIR/evu_json.log"
fi

openwbDebugLog ${DMOD} 2 "Filter Watt : ${bezugjsonwatt}"
openwbDebugLog ${DMOD} 2 "Filter Bezug: ${bezugjsonkwh}"
openwbDebugLog ${DMOD} 2 "Filter Einsp: ${einspeisungjsonkwh}"

python3 /var/www/html/openWB/modules/bezug_json/read_json.py "${bezugjsonurl}" "${bezugjsonwatt}" "${bezugjsonkwh}" "${einspeisungjsonkwh}" >>$MYLOGFILE 2>&1
ret=$?

openwbDebugLog ${DMOD} 2 "RET: ${ret}"

evuwatt=$(</var/www/html/openWB/ramdisk/wattbezug)
echo ${evuwatt}
`

read_json.py:
`#!/usr/bin/env python3

import requests
import sys
import traceback
import jq
from datetime import datetime, timezone
import os

Debug         = int(os.environ.get('debug'))
myPid         = str(os.getpid())

bezugjsonurl = str(sys.argv[1])

bezugjsonwatt = str(sys.argv[2])
bezugjsonkwh = str(sys.argv[3])
einspeisungjsonkwh = str(sys.argv[4])

def DebugLog(message):
        local_time = datetime.now(timezone.utc).astimezone()
        print(local_time.strftime(format = "%Y-%m-%d %H:%M:%S") + ": PID: "+ myPid +": " + message)



if Debug >= 2:
        DebugLog('JQ Watt: ' + bezugjsonwatt)
        DebugLog('JQ Bezug: ' + bezugjsonkwh)
        DebugLog('JQ Einsp: ' + einspeisungjsonkwh)


answer = requests.get(bezugjsonurl, timeout=5).json()
try:
        evuwatt = jq.compile(bezugjsonwatt).input(answer).first()
        with open("/var/www/html/openWB/ramdisk/wattbezug", "w") as f:
                f.write(str(evuwatt))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Watt: ' + str(evuwatt))

try:
        if bezugjsonkwh != "":
                evuikwh = jq.compile(bezugjsonkwh).input(answer).first()
        else:
                evuikwh = 0
        with open("/var/www/html/openWB/ramdisk/bezugkwh", "w") as f:
                f.write(str(evuikwh))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Bezug: ' + str(evuikwh))

try:
        if einspeisungjsonkwh != "":
                evuekwh = jq.compile(einspeisungjsonkwh).input(answer).first()
        else:
                evuekwh = 0
        with open("/var/www/html/openWB/ramdisk/einspeisungkwh", "w") as f:
                f.write(str(evuekwh))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Einsp: ' + str(evuekwh))

exit(0)`

**Comment by DetMoerk** [comment]
Überarbeitet Versionen

main.sh```

#!/bin/bash
OPENWBBASEDIR=$(cd `dirname $0`/../../ && pwd)
RAMDISKDIR="$OPENWBBASEDIR/ramdisk"
MODULEDIR=$(cd `dirname $0` && pwd)
#DMOD="EVU"
DMOD="MAIN"
Debug=$debug

#For development only
#Debug=1

if [ $DMOD == "MAIN" ]; then
        MYLOGFILE="$RAMDISKDIR/openWB.log"
else
        MYLOGFILE="$RAMDISKDIR/evu_json.log"
fi

openwbDebugLog ${DMOD} 2 "Filter Watt : ${bezugjsonwatt}"
openwbDebugLog ${DMOD} 2 "Filter Bezug: ${bezugjsonkwh}"
openwbDebugLog ${DMOD} 2 "Filter Einsp: ${einspeisungjsonkwh}"

python3 /var/www/html/openWB/modules/bezug_json/read_json.py "${bezugjsonurl}" "${bezugjsonwatt}" "${bezugjsonkwh}" "${einspeisungjsonkwh}" >>$MYLOGFILE 2>&1
ret=$?

openwbDebugLog ${DMOD} 2 "RET: ${ret}"

evuwatt=$(</var/www/html/openWB/ramdisk/wattbezug)
echo ${evuwatt}
```


read_json.sh
```
#!/usr/bin/env python3

import requests
import sys
import traceback
import jq
from datetime import datetime, timezone
import os

Debug         = int(os.environ.get('debug'))
myPid         = str(os.getpid())

bezugjsonurl = str(sys.argv[1])

bezugjsonwatt = str(sys.argv[2])
bezugjsonkwh = str(sys.argv[3])
einspeisungjsonkwh = str(sys.argv[4])

def DebugLog(message):
        local_time = datetime.now(timezone.utc).astimezone()
        print(local_time.strftime(format = "%Y-%m-%d %H:%M:%S") + ": PID: "+ myPid +": " + message)



if Debug >= 2:
        DebugLog('JQ Watt: ' + bezugjsonwatt)
        DebugLog('JQ Bezug: ' + bezugjsonkwh)
        DebugLog('JQ Einsp: ' + einspeisungjsonkwh)


answer = requests.get(bezugjsonurl, timeout=5).json()
try:
        evuwatt = jq.compile(bezugjsonwatt).input(answer).first()
        with open("/var/www/html/openWB/ramdisk/wattbezug", "w") as f:
                f.write(str(evuwatt))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Watt: ' + str(evuwatt))

try:
        if bezugjsonkwh != "":
                evuikwh = jq.compile(bezugjsonkwh).input(answer).first()
        else:
                evuikwh = 0
        with open("/var/www/html/openWB/ramdisk/bezugkwh", "w") as f:
                f.write(str(evuikwh))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Bezug: ' + str(evuikwh))

try:
        if einspeisungjsonkwh != "":
                evuekwh = jq.compile(einspeisungjsonkwh).input(answer).first()
        else:
                evuekwh = 0
        with open("/var/www/html/openWB/ramdisk/einspeisungkwh", "w") as f:
                f.write(str(evuekwh))
except:
        traceback.print_exc()
        exit(1)
if Debug >= 1:
        DebugLog('Einsp: ' + str(evuekwh))

exit(0)
```

**Comment by philipp123ow** [comment]
Bei Powerfox hat sich eine Fehlfunktion eingeschlichen. Powerfox liefert alle Werte mit .0 zurück. Wenn diese aber direkt nach Ramdisk weg geschrieben werden kann openWB mit den Werten nicht mehr arbeiten. Wenn man die 3 Werte zuvor in einen Integer umwandelt, funktioniert das ganze wieder. Da als Nachkommastelle (Zumindest bei mir) immer nur die 0 kommt, ist das ganze aber auch kein Problem.

powerfox.py:

`#!/usr/bin/env python3

import requests
import sys
import traceback

powerfoxid = str(sys.argv[1])
powerfoxuser = str(sys.argv[2])
powerfoxpass = str(sys.argv[3])

response = requests.get('https://backend.powerfox.energy/api/2.0/my/'+powerfoxid+'/current', auth=(powerfoxuser, powerfoxpass), timeout=3).json()
try:
    einspeisungwh = response['A_Minus']
    with open("/var/www/html/openWB/ramdisk/einspeisungkwh", "w") as f:
        f.write(str(int(einspeisungwh)))
except:
    traceback.print_exc()

try:
    bezugwh = response['A_Plus']
    with open("/var/www/html/openWB/ramdisk/bezugkwh", "w") as f:
        f.write(str(int(bezugwh)))
except:
    traceback.print_exc()

try:
    watt = response['Watt']
    with open("/var/www/html/openWB/ramdisk/wattbezug", "w") as f:
        f.write(str(int(watt)))
except:
    traceback.print_exc()
`

**Comment by DetMoerk** [comment]
Ich würde mal den Umbau der JSON Module auf JQ übernehmen. Also Speicher, EVU und WR.

**Comment by DetMoerk** [comment]
Ich hab ein der Zwischenzeit einen eigenen PR gestellt, der die generischen JSON Module für PV, EVU und Speicher enthält.

VG
Det

**Comment by DetMoerk** [comment]
Die JSON Module wurden in PR #1530 bereits eingebaut und sind in der Nightly gemerged.

**Pull request merged**
