### PR TITLE
Retry https://github.com/snaptec/openWB/pull/1404

### PR DESCRIPTION
**Pull request by IngmarStein**
The previous version clobbered the config file if the sed pattern contained an error or sed failed for any reason. This attempt writes the result into the target file only if the operation was successful, storing the intermediate result in a temporary file.

This PR creates a new helper function `safeSed` to wrap this series of commands.

### CODE REVIEW

**Comment by yankee42** [comment]
A good thing about the current use of `sed -i` is that the move operation it uses is atomic. If you use `sed -i` and the process crashes (be it because of a bug or be it because of a loss of power) this will not leave a destroyed file behind.

This PR will change that. If the process crashes it may garble to config file.

Why do you need to use a bind mount in the first place? You could just mount the parent directory...

**Comment by IngmarStein** [comment]
The non-atomic part is only `cat`ing the temporary file into the original. Whether that can actually lead to data corruption in case of a loss of power probably depends on many layers, e.g. the file system, buffered I/O, disk buffers, etc, but yeah the risk increases from the status quo.

The config lives in `/var/www/html/openWB` which is not a suitable directory to mount. Moving it somewhere else would be a larger user-visible change for everyone, not just folks who run openWB in container, that's why I refrained from suggesting that. But I agree that a separate place would be a clean solution.

**Comment by IngmarStein** [comment]
Friendly ping. Are you considering merging this as-is, suggest some changes, prefer to move the config file to a mountable location, or keep the status quo (which has the issues mentioned in https://github.com/IngmarStein/openwb-docker/issues/3)?

**Comment by IngmarStein** [comment]
Rebased the PR to resolve conflicts.

**Comment by JSAnyone** [comment]
I would find the docker-implementation very helpful!
However, I understand that both advised solutions aren't optimal, especially considering the fact that the openWB Team focusses it's developers on openWB-Hardware specific topics, which docker definitely isn't.
Also, looking forward to 2.x, the openWB Team seems to be very busy right now.
Would it maybe be possible to design at least openWB 2.x docker-compatible, e.g. with using as advices a config-specific directory for the config file?

**Comment by andig** [comment]
If you need something docker-ready but with different feature set I would recommend evcc

**Comment by JSAnyone** [comment]
I know EVCC, but I really appreciate the variety of features that are part of OpenWB, so it isn't a alternative for me at all.

**Comment by IngmarStein** [comment]
Closed due to lack of interest in supporting a containerized environment.

**Pull request closed without merging**
