### PR TITLE
Integration of Deye SUN600/800/1000G3-EU-230 device series microinverter

### PR DESCRIPTION
**Pull request by tking**
This PR contains the changes for an integration of Deye SUN600/800/1000G3-EU-230 device series microinverters.

Please carefully review if this PR contains all the necessary changes and steps to integrate the new module wr2_deye to openWB.

Thanks for your support!

### CODE REVIEW

**Review by LKuemmel — CHANGES_REQUESTED** [review]
as I mentioned in the forum, only modules are merged in [this](https://github.com/openWB/core/wiki/Neues-Gerät-programmieren) form. Please convert your main.sh script. 
sample_request_per_device might be the right example for you.

**Comment by benderl** [comment]
This module, as implemented now, has much too long runtime!
The ping check takes at least zwo seconds. Then, in worst case, we wait another 25 seconds (5*5s) until the module finishes with no value.
Modules need to return as fast as possible to prevent slowing down the regulation loop too much. This is even more important for openWB 1.9.
Please consider runtime minimization when porting the module as mentioned by Lena.

**Comment by tking** [comment]
> as I mentioned in the forum, only modules are merged in [this](https://github.com/openWB/core/wiki/Neues-Ger%C3%A4t-programmieren) form. Please convert your main.sh script. sample_request_per_device might be the right example for you.

Thanks for the feedback. I understood the discussion in the forum in such a way that the main.sh script is still okay for version 1.9. This is what hhoefling wrote.

**Comment by tking** [comment]
> This module, as implemented now, has much too long runtime! The ping check takes at least zwo seconds. Then, in worst case, we wait another 25 seconds (5*5s) until the module finishes with no value. Modules need to return as fast as possible to prevent slowing down the regulation loop too much. This is even more important for openWB 1.9. Please consider runtime minimization when porting the module as mentioned by Lena.

I changed the parameters to reduce the time needed. The ping count is now 1. The retry is now 2 meaning at maximum 2 readings are taken. Are these values okay with you?

**Comment by tking** [comment]
> > > as I mentioned in the forum, only modules are merged in [this](https://github.com/openWB/core/wiki/Neues-Ger%C3%A4t-programmieren) form. Please convert your main.sh script. sample_request_per_device might be the right example for you.
> > 
> > 
> > Thanks for the feedback. I understood the discussion in the forum in such a way that the main.sh script is still okay for version 1.9. This is what hhoefling wrote.
> 
> No, new modules have to be compatible with 1.9 and 2.0. Please follow the link Lena has posted.

I already worked on the python based implementation:
https://github.com/tking/core/tree/master/packages/modules/devices/deye

Your feedback is highly appreciated!

Best regards
Thomas

**Comment by benderl** [comment]
Please open a new PR from your branch.

**Pull request closed without merging**
