### PR TITLE
Allow spaces for discovergypass

### PR DESCRIPTION
**Pull request by foscoj**
Together with #1203 and #1202 this change should allow spaces in discovergy passwords

Untested, assumption after reading code. Eager to test as nightly on my original box!

### CODE REVIEW

**Comment by benderl** [comment]
Modifications to the default openwb.conf will not update entries on existing installations. Please have a look at `runs/updateConfig.sh` how to add or update existing settings.

**Comment by foscoj** [comment]
> Modifications to the default openwb.conf will not update entries on existing installations. Please have a look at `runs/updateConfig.sh` how to add or update existing settings.

As far as I understand the logic of `runs/updateConfig.sh`, existing passwords would be reset if I only echo some default into the variable. Is there any chance to preserve existing passwords, so existing configurations with discovergy won't break?

**Comment by benderl** [comment]
Simply check for an entry without quotes and add them around the value.
This should do the trick:
`sed -i "s/^discovergypass=\(.*\)/discovergypass=\'\1\'/g" ./openwb.conf`

**Comment by foscoj** [comment]
> Simply check for an entry without quotes and add them around the value.
> This should do the trick:
> `sed -i "s/^discovergypass=\(.*\)/discovergypass=\'\1\'/g" ./openwb.conf`

Thanks. I will debug the regex later, currently it will add single quotes to existing ones as well. Another opportunity to learn these damn useful regex (again) 😉

**Comment by benderl** [comment]
Should already work, as single quotes don't match.
This is helpfull: https://regexr.com/

**Comment by foscoj** [comment]
`sed -i "/discovergypass='/b; s/^discovergypass=\(.*\)/discovergypass=\'\1\'/g" ./openwb.conf` should be the right command to preserve already existing single quotes without adding another pair.  fixed in #1218

**Comment by foscoj** [comment]
Sry for using German. The switch to anything different than Discovergy seems to be impossible. 
Trying with backup of old version and setting the password to something without spaces.

**Comment by foscoj** [comment]
Ok, tried a backup, everything is fine, but regardless what kind of EVU I select (tried not available to be sure) I am not able to change anything through save after the update an no parameters are possible in current nightly. Might this be somehow connected to my PRs or is this a completely different issue?

**Comment by benderl** [comment]
Was an missing "}" after another merge.

**Comment by foscoj** [comment]
> Was an missing "}" after another merge.

Thanks, it's working :-)

**Pull request merged**
