### PR TITLE
Code deduplication in modulconfig.php

### PR DESCRIPTION
**Pull request by david-m-m**
Hi,

I noticed that in web/modulconfig.php there is a lot of code duplication. To make it a bit more understandable and maintainable I took the freedom of reducing that duplication. 
Now in each block handling the visuals is structured like this:

- function to encapsulate the visuals handling (`display_*`)
  - first hide all elements
  - then walk through the options and display elements accordingly
- anonymous function calls `display_*`
  - when entering
  - when change is triggered

Adding more elements should now be much easier:

- add element once in the "hide" list
- add if statement to display when needed

I hope you find this simplification helpful and will accept it in the code. 
However I recommend testing it before integrating (I still might have overlooked some typos)

Best regards, David

### CODE REVIEW

**Comment by david-m-m** [comment]
@snaptec Is this something you find helpful? If so, I'd update the PR to include the changes that have been made in the meantime. :-)

**Comment by snaptec** [comment]
Sorry, I missed that PR a bit. Saw it, changed something in modulconfig and wanted to fix that "tomorrow". Definately a really good one.
Please update it and I will merge it directly.

**Comment by david-m-m** [comment]
Hi @snaptec,

> Sorry, I missed that PR a bit. Saw it, changed something in modulconfig and wanted to fix that "tomorrow". Definately a really good one.
> Please update it and I will merge it directly.

no problem. I had a pretty busy time in the last weeks so it took me a while to update the PR. 

I think the current version should have everything included, but I recommend you have another look at it before merging. 

Greetings, David

**Comment by david-m-m** [comment]
Still has merge conflicts. I close this one an reopen a fresh PR...

**Pull request closed without merging**
