### PR TITLE
Deduplicate code in function sepwatt in smarthomehandler.py

### PR DESCRIPTION
**Pull request by fawick**
This is primarily to reduce the number of lines to maintain as well as making it easier to add additional device types in the future.

### CODE REVIEW

**Comment by fawick** [comment]
@okaegi Would you kindly give this change a testdrive against your Shelly devices, too?

**Comment by okaegi** [comment]
Not good 
  File "/var/www/html/openWB/runs/smarthomehandler.py", line 82
    else if meastyp == "shelly":
          ^
SyntaxError: invalid syntax
Please use elif instead of else if

**Comment by okaegi** [comment]
Otherwise it works

**Comment by fawick** [comment]
Thanks a lot @okaegi, I pushed a fix. Hopefully those mistakes will no longer occur now that I have SSH access to my openWB.

**Pull request merged**
