### PR TITLE
soc_vwid: remove obsolete soc_id module

### PR DESCRIPTION
**Pull request by rleidner**
PR removes the obsolete SOC module soc_id (VW ID-alt - based on obsolete evcc-soc binary).
The configuration parameters of soc_id are used in the current soc_vwid module. 
Therefore no changes in config scripts.

### CODE REVIEW

**Comment by benderl** [comment]
Please also remove the module for charge point 2.

**Comment by rleidner** [comment]
Thanks for the pointer. soc_idlp2 is removed now.

**Comment by benderl** [comment]
And another change request:
Please update selected soc modules in `runs/updateConfig.sh`.
Something like this for both charge points:
```
if grep -Fq "socmodul=soc_id" $ConfigFile; then
	sed -i "s/^socmodul=soc_id/socmodul=soc_vwid/g" $ConfigFile
fi
if grep -Fq "socmodul1=soc_idlp2" $ConfigFile; then
	sed -i "s/^socmodul1=soc_idlp2/socmodul=soc_vwidlp2/g" $ConfigFile
fi
```

**Comment by rleidner** [comment]
update configuration in updateConfig.sh done

**Pull request merged**
