### PR TITLE
make SolarEdge port number configurable

### PR DESCRIPTION
**Pull request by tomvo12**
We have a newer SolarEdge installation which uses port 1502 for MODBUS access instead of 502. So we made this port value configurable in the module configuration.
Please have a look and let me know, if this is acceptable.

Cheers,
Tom Voss

### CODE REVIEW

**Comment by snaptec** [comment]
You should have asked before. 
There is Standard - Port 502. 
Every SolarEdge electrician gets the Info to configure it that way. 
I think it's too confusing having here another var.

**Comment by tomvo12** [comment]
Well, our SolarEdge installation (we have two of them and 6 openWB boxes) obviously does not use the old standard port 502 but the newer 1502. I think, there have been others asking for this feature as well.
I also chose 502 as standard setting and made sure that only "502 or "1502" can be entered here. This change would enable us to use the power management which was the original reason to buy 6 boxes.
I also do not see, why a single port number setting which is described in the UI could be "too confusing". But if so, may be it could be put into an advanced dialog.

**Comment by snaptec** [comment]
Newer is not quite the correct answer.

> I also do not see, why a single port number setting which is described in the UI could be "too confusing". But if so, may be it could be put into an advanced dialog.
Just experiences from support

Idea:
Lets auto negotiate this. F.e.:
`
try:
    read Ramdisk/SEPort (empty after boot)
except:
    try:
        connect port 502
        write 502 -> ramdisk/SEPort
    except:
        tologfile: port 502 closed
    try:
        connect port 1502
        write 1502 -> ramdisk/SEPort
    except:
        tologfile: port 1502 closed, wrong ip? modbus disabled?
`

**Comment by tomvo12** [comment]
Ok, sounds reasonable. I have to figure out how and where to do exactly and give it a try.

Thanks,
Tom

**Pull request closed without merging**
